[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.build]
cmds = ["cd 'Prototype Template for Extreme Platform ONE' && npm install && npm run build"]

[start]
cmd = "cd 'Prototype Template for Extreme Platform ONE' && npx serve -s build -l $PORT"
